/*
 * Neo Backup: open-source apps backup and restore app.
 * Copyright (C) 2020  Antonios Hazim
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.machiav3lli.backup.utils

import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import timber.log.Timber
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * A [SharedPreferences] implementation that encrypts every stored value with an
 * [android.security.keystore.KeyStore]-backed AES-256/GCM key (alias never leaves the secure
 * hardware/keystore). It is the replacement for the deprecated, unmaintained
 * `androidx.security:security-crypto` `EncryptedSharedPreferences`.
 *
 * Design:
 *  - Values are serialized to their string form, encrypted as `IV‖ciphertext‖tag` and stored
 *    Base64-encoded in a plain backing [SharedPreferences] file.
 *  - A fresh random 96-bit GCM IV is generated by the cipher for every write, so the same
 *    value never encrypts to the same bytes and no IV is reused with the keystore key.
 *  - Key names are stored in the clear (the private-pref key names - e.g. the password key -
 *    are not secret; only their values are).
 *  - Each value carries a 128-bit GCM authentication tag, so tampering is detected on read
 *    (a failed decryption falls back to the caller's default value).
 */
class KeystoreEncryptedPreferences(
    private val backing: SharedPreferences,
    private val keyAlias: String,
) : SharedPreferences {

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getEntry(keyAlias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                keyAlias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private fun encrypt(plain: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv
        val cipherText = cipher.doFinal(plain.toByteArray(Charsets.UTF_8))
        val out = ByteArray(iv.size + cipherText.size)
        System.arraycopy(iv, 0, out, 0, iv.size)
        System.arraycopy(cipherText, 0, out, iv.size, cipherText.size)
        return Base64.encodeToString(out, Base64.NO_WRAP)
    }

    private fun decrypt(stored: String?): String? {
        if (stored == null) return null
        return try {
            val data = Base64.decode(stored, Base64.NO_WRAP)
            if (data.size <= GCM_IV_LENGTH) return null
            val iv = data.copyOfRange(0, GCM_IV_LENGTH)
            val cipherText = data.copyOfRange(GCM_IV_LENGTH, data.size)
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
            String(cipher.doFinal(cipherText), Charsets.UTF_8)
        } catch (e: Throwable) {
            Timber.e("Private prefs: could not decrypt value for a key: ${e.message}")
            null
        }
    }

    override fun getAll(): MutableMap<String, *> =
        backing.all.keys.associateWith { key -> decrypt(backing.getString(key, null)) }
            .toMutableMap()

    override fun getString(key: String, defValue: String?): String? =
        decrypt(backing.getString(key, null)) ?: defValue

    override fun getStringSet(key: String, defValues: MutableSet<String>?): MutableSet<String>? =
        PrefValueCodec.decodeStringSet(decrypt(backing.getString(key, null))) ?: defValues

    override fun getInt(key: String, defValue: Int): Int =
        PrefValueCodec.decodeInt(decrypt(backing.getString(key, null)), defValue)

    override fun getLong(key: String, defValue: Long): Long =
        PrefValueCodec.decodeLong(decrypt(backing.getString(key, null)), defValue)

    override fun getFloat(key: String, defValue: Float): Float =
        PrefValueCodec.decodeFloat(decrypt(backing.getString(key, null)), defValue)

    override fun getBoolean(key: String, defValue: Boolean): Boolean =
        PrefValueCodec.decodeBoolean(decrypt(backing.getString(key, null)), defValue)

    override fun contains(key: String): Boolean = backing.contains(key)

    override fun edit(): SharedPreferences.Editor = Editor()

    // The private vault has no observers in this app; keep the listener API as a safe no-op.
    override fun registerOnSharedPreferenceChangeListener(
        listener: SharedPreferences.OnSharedPreferenceChangeListener?,
    ) = Unit

    override fun unregisterOnSharedPreferenceChangeListener(
        listener: SharedPreferences.OnSharedPreferenceChangeListener?,
    ) = Unit

    inner class Editor : SharedPreferences.Editor {
        private val editor = backing.edit()

        private fun putEncrypted(key: String, value: String): SharedPreferences.Editor {
            editor.putString(key, encrypt(value))
            return this
        }

        override fun putString(key: String, value: String?): SharedPreferences.Editor =
            if (value == null) remove(key) else putEncrypted(key, value)

        override fun putStringSet(
            key: String,
            values: MutableSet<String>?,
        ): SharedPreferences.Editor =
            if (values == null) remove(key)
            else putEncrypted(key, PrefValueCodec.encodeStringSet(values))

        override fun putInt(key: String, value: Int): SharedPreferences.Editor =
            putEncrypted(key, PrefValueCodec.encode(value))

        override fun putLong(key: String, value: Long): SharedPreferences.Editor =
            putEncrypted(key, PrefValueCodec.encode(value))

        override fun putFloat(key: String, value: Float): SharedPreferences.Editor =
            putEncrypted(key, PrefValueCodec.encode(value))

        override fun putBoolean(key: String, value: Boolean): SharedPreferences.Editor =
            putEncrypted(key, PrefValueCodec.encode(value))

        override fun remove(key: String): SharedPreferences.Editor {
            editor.remove(key)
            return this
        }

        override fun clear(): SharedPreferences.Editor {
            editor.clear()
            return this
        }

        override fun commit(): Boolean = editor.commit()

        override fun apply() = editor.apply()
    }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_LENGTH = 12
        private const val GCM_TAG_BITS = 128
    }
}
